### ISSUE TITLE
Stuck when enabling extension

### ISSUE THREAD

**Issue by tapiov** [softedco/GameJolt-API-Scratch-extension#1]
Hi. Not sure I am using this right but when I try to use the extension this happens
1. Create a Turbowarp project
2. Test the project in Packager preview => works
3. Add to Advanced Options, Custom extensions: 
https://softedco.github.io/GameJolt-API-Scratch-extension/GameJoltAPI.js
4. Test the project in Packager preview => stucks to loading screen, something like 95% complete

Tried also packaging, Plain HTML, ZIP, uploaded to GameJolt. Same result as in 4.

Probably something I am doing wrong?

**Comment by tapiov** [comment]
OK, I got it working by copy+pasting the full JS to box 
Custom JS (Don't change if you don't know what you're doing!)
So it's the format I am using in the Custom Extensions above that

**Comment by softedco** [comment]
The extension won't load from a link in the packager, but it will work if you paste the code into the custom js box

**Comment by softedco** [comment]
This link will work if you add -Unsandboxed in the end, it would look something like this:
https://softedco.github.io/GameJolt-API-Scratch-extension/GameJoltAPI-Unsandboxed.js
But I don't recommend doing that since your project might break.
